export const ROUTES = {
  home: "/",
  donar: "/donar",
  centros: "/centros",
  crearCentro: "/centros/nuevo",
  misCentros: "/mis-centros",
  misCentroDetalle: (id: string) => `/mis-centros/${id}`,
  misCentroEditar: (id: string) => `/mis-centros/${id}/editar`,
  invitarVoluntarios: (id: string) => `/mis-centros/${id}/invitar`,
  gestionarVoluntarios: (id: string) => `/mis-centros/${id}/voluntarios`,
  unirse: (token: string) => `/unirse/${token}`,
  nuevoEnvio: (centroId: string) => `/envios/nuevo?centro=${centroId}`,
  escanearDonacion: (centroId: string) => `/scanning?centro=${centroId}`,
  cargarInventario: (id: string) => `/mis-centros/${id}/cargar`,
  inventario: "/inventario",
  scanning: "/scanning",
} as const;
