export const ROUTES = {
  home: "/",
  donar: "/donar",
  centros: "/centros",
  centroDetalle: (id: string) => `/centros/${id}`,
  crearCentro: "/centros/nuevo",
  misCentros: "/mis-centros",
  misCentroDetalle: (id: string) => `/mis-centros/${id}`,
  misCentroEditar: (id: string) => `/mis-centros/${id}/editar`,
  invitarVoluntarios: (id: string) => `/mis-centros/${id}/invitar`,
  gestionarVoluntarios: (id: string) => `/mis-centros/${id}/voluntarios`,
  configurarUmbrales: (id: string) => `/mis-centros/${id}/umbrales`,
  reporteInventario: (id: string) => `/reporte/${id}`,
  unirse: (token: string) => `/unirse/${token}`,
  nuevoEnvio: (centroId: string) => `/envios/nuevo?centro=${centroId}`,
  escanearDonacion: (centroId: string) => `/scanning?centro=${centroId}`,
  mapa: "/mapa",
  scanning: "/scanning",
  faq: "/faq",
} as const;
